DROP DATABASE IF EXISTS Employee_DB;
CREATE DATABASE Employee_DB;

USE Employee_DB;

CREATE TABLE department (
    id INTEGER(11) AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR (40) NOT NULL 
);

CREATE TABLE roles (
id INTEGER (11) AUTO_INCREMENT PRIMARY KEY,
title VARCHAR (40) NOT NULL,
salary DECIMAL,
department_id INTEGER,
CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES department(id) ON DELETE SET NULL
);


CREATE TABLE employee (
id INTEGER (11) AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
roles_id INTEGER,
department_id INTEGER,
salary DECIMAL,
manager VARCHAR(30),
CONSTRAINT fk_roles FOREIGN KEY (roles_id) REFERENCES roles(id)  ON DELETE CASCADE,
manager_id INTEGER,
CONSTRAINT fk_manager FOREIGN KEY (manager_id) REFERENCES employee(id) ON DELETE  SET NULL

);

